### ISSUE TITLE
Efficient conversion to sf objects

### ISSUE THREAD

**Issue by dylanbeaudette** [dfriend21/quadtree#12]
Thanks for this awesome package! I've been wanting to do this in R for a very long time.

Tinkering with the CRAN version I could not figure out how to efficiently convert a quadree object to sf object. I may have overlooked something obvious. Here is a FAST solution that I came up with in case you find it useful. The {wk} and {data.table} packages improved the collation + flattening of cells into a single {sf} object.

```r
# https://www.sciencedirect.com/science/article/pii/S0098300406001828?via%3Dihub
# https://www.cabdirect.org/cabdirect/abstract/20013118404
# https://link.springer.com/content/pdf/10.1007/BF02083652.pdf

# https://dfriend21.github.io/quadtree/index.html

library(soilDB)
library(raster)
library(rasterVis)
library(sf)
library(wk)
library(data.table)
library(quadtree)

# make a bounding box and assign a CRS (4326: GCS, WGS84)
a.CA <- st_bbox(
  c(xmin = -2280334, xmax = -2065433, ymin = 1755361, ymax = 1970262), 
  crs = st_crs(5070)
)

# convert bbox to sf geometry
a.CA <- st_as_sfc(a.CA)


pH_3060cm <- ISSR800.wcs(aoi = a.CA, var = 'ph_3060cm')
plot(pH_3060cm, axes = FALSE, xlab = '', ylab = '')


qt <- quadtree(pH_3060cm, split_threshold = 0.25, split_method = "sd", adj_type = "resample",  resample_n_side = 128)


par(mar = c(0, 1, 0, 0), bg = 'black', mfcol = c(1, 2))
plot(pH_3060cm, axes = FALSE, xlab = '', ylab = '', legend = FALSE, col = viridis::viridis(100))
plot(qt, axes = FALSE, xlab = '', ylab = '', legend = FALSE, col = viridis::viridis(100), border_col = 'white', na_col = 'black', crop = TRUE)

r <- as_raster(qt, pH_3060cm)

par(mar = c(0, 1, 0, 0), bg = 'black', mfcol = c(1, 2))
plot(pH_3060cm, axes = FALSE, xlab = '', ylab = '', legend = FALSE, col = viridis::viridis(100))
plot(r, axes = FALSE, xlab = '', ylab = '', legend = FALSE, col = viridis::viridis(100))


df <- as_data_frame(qt, FALSE)

# iterate over boxes -> single sf object
# ~ 5 seconds with wk
v <- lapply(1:nrow(df), function(i) {
  
  .row <- df[i, ]
  
  ## this is very slow
  # st_bbox -> st_as_sfc -> st_as_sf
  
  # fast BBOX -> SF via wk
  
  # BBOX -> WK
  .bbox <- rct(
    xmin = .row$xmin, xmax = .row$xmax, ymin = .row$ymin, ymax = .row$ymax, 
    crs = st_crs(5070)
  )
  
  # WK -> SF
  return(st_as_sf(.bbox))
})

# rbind.sf is slow for > 1,000 objects
# v <- do.call('rbind', v)library(wk)

# ! 3 seconds
# https://github.com/r-spatial/sf/issues/798
v <- st_as_sf(data.table::rbindlist(v))


dev.off()

par(mar = c(0, 0, 0, 0) + 0.125, bg = 'black')
plot(pH_3060cm, axes = FALSE, xlab = '', ylab = '', legend = FALSE, col = viridis::viridis(100))
plot(v, border = 'white', add = TRUE)
```

**Comment by dfriend21** [comment]
Thanks for posting and for the code!  Honestly I hadn't given data type conversions much thought before now, but that's something I should definitely add - I'll make an issue for it so that I remember to add it at some point. It'd definitely be nice to have a function that just converts it to an `sf` object.

I've fiddled around with your code - I'm not all that familiar with `sf` or `wk`, but I was able to modify your code to use `data.table` to create the rectangles, and it seems to run considerably faster:

```r
library(soilDB)
library(sf)
library(wk)
library(data.table)
library(quadtree)

# make a bounding box and assign a CRS (4326: GCS, WGS84)
a.CA <- st_bbox(
  c(xmin = -2280334, xmax = -2065433, ymin = 1755361, ymax = 1970262), 
  crs = st_crs(5070)
)

# convert bbox to sf geometry
a.CA <- st_as_sfc(a.CA)

pH_3060cm <- ISSR800.wcs(aoi = a.CA, var = 'ph_3060cm')
plot(pH_3060cm, axes = FALSE, xlab = '', ylab = '')

qt <- quadtree(pH_3060cm, split_threshold = 0.25, split_method = "sd", adj_type = "resample",  resample_n_side = 128)

dt <- data.table(as_data_frame(qt))
cr <- st_crs(5070)
bbs_list <- dt[, list(bb = st_as_sf(rct(xmin, ymin, xmax, ymax, cr)))]$bb

bbs <- st_as_sf(bbs_list)
plot(bbs)
```


I ran a quick benchmark on it, and it was taking 163ms on my machine. So give that a shot and see if it works for you.

**Comment by dylanbeaudette** [comment]
Thanks! Your code is much faster / elegant that the hack I posted. What do you think about splitting categorical rasters based on Shannon entropy?

**Comment by dfriend21** [comment]
That's not something I'm very familiar with... looks like it's an index for the variation in categorical data - is that correct? So the idea would be to split a quadrant if the variation is above some threshold - otherwise you'd assign the most common category to the cell? Am I interpreting that correctly?

It'd definitely be nice to add more support for categorical data. My use case for creating the package was entirely with continuous rasters, so I didn't give any thought to categorical data when writing the code. If that's something you think would be a useful addition I could certainly add an option for splitting based on the Shannon entropy - I don't think it'd be too difficult. That being said, I don't have a plethora of spare time these days (and won't for the next several months) so I can't guarantee that I'd get to it in a timely fashion - but I can certainly add it to the to-do.

For what it's worth, you should be able create a custom function that implements the Shannon entropy. You can write functions to define your own rules for splitting cells - see [this section](https://dfriend21.github.io/quadtree/articles/quadtree-creation.html#splitting-functions-1) of the "Creating Quadtrees" vignette.

**Comment by dfriend21** [comment]
Functionality added in PR #17
